### ISSUE TITLE
Window cropped.

### ISSUE THREAD

**Issue by jsanchezfr** [WindowsNT/ColorPicker#1]
When Windows Destop scale isn't 100%:
![Captura](https://user-images.githubusercontent.com/25683502/86770684-576f0900-c051-11ea-8920-5011e31a4054.PNG)

The application window is cropped when displayed:
![Captura2](https://user-images.githubusercontent.com/25683502/86770685-58079f80-c051-11ea-80f1-3e227ad17db2.PNG)

**Comment by WindowsNT** [comment]
I will take a look, thanks for the note.

**Comment by jsanchezfr** [comment]
I solved (temporaly) adding:

            d->SetDpi(96.0, 96.0);

Before:
            d->BeginDraw();
            Paint(fa, WriteFactory, d, rc);
            d->EndDraw();
            EndPaint(hh, &ps);
            return 0;

In WM_PAINT

**Comment by WindowsNT** [comment]
I also used this, basically it's because I use the older ID2D1RenderTarget.
If you use the ID2D1DeviceContext it's OK.
