### ISSUE TITLE
Help with usage what goes in {...}

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [WindowsNT/ColorPicker#2]
Hello I am having a bit of trouble getting the color to return I am a a little new to this D2D1 in general.

the instructions say easy to use
#include "colorpick.hpp"
COLORPICK p;
D2D1_COLOR_F c1 = {1.0f,0,0,1.0f}; // init with red
HRESULT hr = p.Show(0, c);
if (hr == S_OK) { ... } // Color is set

What am I supposed to put in the   "{ ... } // Color is set "
if (hr == S_OK) { ... } // Color is set

How do I set the/a color here I am wondering..

Also should it not be
HRESULT hr = p.Show(0, c1);

instead of 

HRESULT hr = p.Show(0, c);

Is this a typo or is there a c I am taking this from the original instructions.

Is c1 the color being set sorry but I can't get it to actually return a color back not sure what goes in {...} or is suppose to go in there to set a D2D1 color. Any help would be appreciated thanks!!

**Comment by WindowsNT** [comment]
If the function returns S_OK, then the user didn't cancel the dialog. That means that you can use the returned color which is returned in the 'c1' (typo, yes, should be c1 instead of c).

**Comment by DavidsonAudioMulti** [comment]
so it should look like this? I am having trouble assigning the color
k

```

		COLORPICK p;

		D2D1_COLOR_F c1{ 1.0f,1.0f,0,1.0f };
		LRESULT hr = p.Show(0, c1);
		if (hr == S_OK) { c1}; // Color is set
```

**Comment by WindowsNT** [comment]
yes, if (hr == S_OK) then c1 was modified by the user.

**Comment by DavidsonAudioMulti** [comment]
Ok I see this works I am trying to get it to convert to a hex value like this with the alpha #AARRGGBB I have been able to turn it into a this but how do I save this color when the color picker opens again. So that I can start from this color and not reset from default color??? thanks!!!

```
code

		COLORPICK p;

		D2D1_COLOR_F c1{  };
		LRESULT hr = p.Show(0, c1);
		if (hr == S_OK) {

		};// Color is set

		DWORD r = RGB((int)(c1.r * 255.0f), (int)(c1.g * 255.0f), (int)(c1.b * 255.0f));
		if (c1.a)
			r |= ((unsigned int)(c1.a * 255.0f) << 24);

		int decimal = r;
		wstringstream my_ss;
		my_ss << hex << decimal;
		wstring res = my_ss.str();
		

		std::wstring wstr = res;



```

**Comment by DavidsonAudioMulti** [comment]
This issue has been completely resolved  thank you!!
